#!/bin/bash

ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/VSCode/settings.json ~/Library/Application\ Support/Code/User/settings.json

git config --global include.path "~/dotfiles/.gitconfig"

if [ $SPIN ]; then
  DOTFILES_DIR=~/dotfiles

  gpgconf --launch dirmngr
  gpg --keyserver keys.openpgp.org --recv C052E21901C94FD88BED425C766F0AF3490749E4
else
  DOTFILES_DIR=~/.dotfiles
fi

for i in $DOTFILES_DIR/dotfiles/*; do
  echo "Installing $(basename $i)..."
  rm -rf ~/.$(basename $i)
  ln -s $i ~/.$(basename $i)
done
